[package]
name = "rustygon"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.12.0"
clap = { version = "4.5.30", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] } 
serde_json = "1.0.138"
